# Generated by Django 3.2.9 on 2021-12-21 01:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prac', '0002_auto_20211218_1555'),
    ]

    operations = [
        migrations.RenameField(
            model_name='choice',
            old_name='choice1_result',
            new_name='choice1',
        ),
        migrations.RenameField(
            model_name='choice',
            old_name='choice2_result',
            new_name='choice2',
        ),
    ]
