# Generated by Django 3.2.9 on 2021-12-21 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prac', '0004_auto_20211220_2026'),
    ]

    operations = [
        migrations.AddField(
            model_name='choice',
            name='choice1_results',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='choice',
            name='choice2_results',
            field=models.IntegerField(default=0),
        ),
    ]
