# Generated by Django 3.2.9 on 2021-12-21 08:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prac', '0005_auto_20211220_2321'),
    ]

    operations = [
        migrations.RenameField(
            model_name='choice',
            old_name='choice1',
            new_name='choice',
        ),
        migrations.RenameField(
            model_name='choice',
            old_name='choice1_results',
            new_name='results',
        ),
        migrations.RemoveField(
            model_name='choice',
            name='choice2',
        ),
        migrations.RemoveField(
            model_name='choice',
            name='choice2_results',
        ),
    ]
